In [1]:
import pandas as p

## Q1. List any five functions of the pandas library with execution.

#### 1)p.DataFrames()
 this function creates new dataframe(table like format of data.

In [2]:
data={'Name':['rohan','sahil'],'mail':['rohan@123','sahil@321']}

In [3]:
df=p.DataFrame(data)

In [4]:
df

    Name       mail
0  rohan  rohan@123
1  sahil  sahil@321

#### 2) .drop()  => Drop specified labels from rows or columns.

In [5]:
df.drop('mail',axis=1,inplace=True)

In [6]:
df

    Name
0  rohan
1  sahil

In [7]:
df1=p.read_csv("services.csv")

In [8]:
df1

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

#### 3) .set_index()

In [9]:
df1.set_index('audience').head()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,description,eligibility,email,fees,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
audience,,,,,,,,,,,,,,,,,,,,,
"Older adults age 55 or over, ethnic minorities and low-income persons",1,1,NaN,NaN,NaN,Walk in or apply by phone.,A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,$2.50 suggested donation for lunch for age 60 ...,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
Residents of San Mateo County age 55 or over,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,None. Donations requested of clients who can a...,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
Older adults age 55 or over who can benefit from counseling,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,None.,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
"Parents, children, families with problems of custody disputes, domestic violence or substance abuse, families going through a separation or divorce",4,4,NaN,NaN,NaN,Apply by phone.,Provides supervised visitation services and a ...,None,NaN,"Vary according to income ($5-$90). Cash, check...",...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
Low-income working families with children transitioning from welfare to work and poor or who do not have access to conventional credit,5,5,NaN,NaN,NaN,Phone for information.,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,$60 application fee. Cash or checks accepted.,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

#### 4) .dropna()

In [10]:
df1.dropna(axis=1)

,id,location_id,application_process,description,name,status
0,1,1,Walk in or apply by phone.,A walk-in center for older adults that provide...,Fair Oaks Adult Activity Center,active
1,2,2,Apply by phone for an appointment.,Provides training and job placement to eligibl...,Second Career Employment Program,active
2,3,3,Phone for information (403-4300 Ext. 4322).,Offers supportive counseling services to San M...,Senior Peer Counseling,active
3,4,4,Apply by phone.,Provides supervised visitation services and a ...,Family Visitation Center,active
4,5,5,Phone for information.,Provides fixed 8% short term loans to eligible...,Economic Self-Sufficiency Program,active
5,6,6,Walk in or apply by phone for membership appli...,A multipurpose center offering a wide variety ...,Little House Recreational Activities,active
6,7,7,"Apply by phone or be referred by a doctor, soc...",Rosener House is a day center for older adults...,Rosener House Adult Day Services,active
7,8,8,Apply by phone.,Delivers a hot meal to the home of persons age...,Meals on Wheels - South County,active
8,9,9,Walk in. Proof of residency in California requ...,"Provides general reading material, including b...",Fair Oaks Branch,active
9,10,10,Walk in. Proof of California residency to rece...,"Provides general reading and media materials, ...",Main Library,active
10,11,11,Walk in. Proof of California residency require...,"Provides general reading materials, including ...",Schaberg Branch,active
11,12,12,"Walk in or apply by phone, email or webpage re...",Offers an intergenerational literacy program f...,Project Read,active
12,13,13,Walk in. Proof of California residency require...,"Provides general reading materials, including ...",Redwood Shores Branch,active
13,14,14,Call for appointment. Referral from human serv...,"Provides food, clothing, bus tokens and shelte...",Redwood City Corps,active
14,15,15,Walk in or through other agency referral.,Provides a long-term (6-12 month) residential ...,Adult Rehabilitation Center,active
15,16,16,"Walk in. Written application, identification r...",Provides emergency assistance including food a...,Sunnyvale Corps,active
16,17,17,Call for information.,"Provides emergency food, clothing and furnitur...",South San Francisco Citadel Corps,active
17,18,18,Call for screening appointment. Medical visits...,"By appointment only, Project Smile provides a ...",Project Smile,active
18,19,19,Call for screening appointment (650-347-3648).,Provides free medical and dental care to those...,San Mateo Free Medical Clinic,active
19,20,20,Walk in.,no unrequired fields for this service,Service with blank fields,defunct
20,21,21,By phone during business hours.,just a test service,Service for Admin Test Location,inactive
21,22,22,Walk in or apply by phone or mail,[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,Passport Photos,active
22,23,22,Walk in or apply by phone or mail,[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,Example Service Name,active

#### 5).groupby()

In [11]:
obj=df1.groupby('status')

In [12]:
obj.mean()

/tmp/ipykernel_70/1582909037.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  obj.mean()

                 id  location_id  program_id
status
active    11.190476    11.142857         NaN
defunct   20.000000    20.000000         NaN
inactive  21.000000    21.000000         NaN

## Q2. Given a Pandas DataFrame df with columns 'A', 'B', and 'C', write a Python function to re-index the DataFrame with a new index that starts from 1 and increments by 2 for each row.

In [13]:
data1={'a':['w','x','y','z'],'b':['a','b','c','d'],'c':['l','m','n','o']}

In [14]:
df=p.DataFrame(data1)

In [15]:
df

   a  b  c
0  w  a  l
1  x  b  m
2  y  c  n
3  z  d  o

In [16]:

def reind(df):
    new_index = range(1, 2 * len(df) + 1, 2)
    df.set_index(p.Index(new_index), inplace=True)
    return df

In [17]:
df=reind(df)

In [18]:
df

   a  b  c
1  w  a  l
3  x  b  m
5  y  c  n
7  z  d  o

In [19]:
len(df)

4

## Q3. You have a Pandas DataFrame df with a column named 'Values'. Write a Python function that iterates over the DataFrame and calculates the sum of the first three values in the 'Values' column. The function should print the sum to the console.
#### For example, if the 'Values' column of df contains the values [10, 20, 30, 40, 50], your function should calculate and print the sum of the first three values, which is 60.

In [20]:
d=[10,20,30,40,50]
df=p.DataFrame({"values":d})

In [21]:
def calculate(df):
    cunt=0
    for i in df['values'][0:3]:
        cunt+=i
    print(cunt)

In [22]:
calculate(df)

60

## Q4. Given a Pandas DataFrame df with a column 'Text', write a Python function to create a new column

In [23]:
text=['abc','def','ghi','jkl','mno']
df2=p.DataFrame({'Text':text})

In [24]:
def add_col(df):
    col_name=input("Enter column name")
    df[col_name]=df['Text'].apply(lambda x:len(x))
    return df

In [25]:
add_col(df2)

Enter column name Text length

  Text  Text length
0  abc            3
1  def            3
2  ghi            3
3  jkl            3
4  mno            3

## Q5. How are DataFrame.size() and DataFrame.shape() different?

DataFrame.size(): This method returns the total number of elements in the DataFrame.i.e it returns the product of the number of rows and columns in the DataFrame.

DataFrame.shape(): This method returns a tuple of two values: The number of rows is given by the first element of the tuple and the number of columns by the second element.

## Q6. Which function of pandas do we use to read an excel file?

To read an exel file we use read_exel() method . example df=pandas.read_exel('filename.xlsx')

## Q7. You have a Pandas DataFrame df that contains a column named 'Email' that contains email addresses in the format 'username@domain.com'. Write a Python function that creates a new column 'Username' in df that contains only the username part of each email address.
## The username is the part of the email address that appears before the '@' symbol. For example, if the email address is 'john.doe@example.com', the 'Username' column should contain 'john.doe'. Your function should extract the username from each email address and store it in the new 'Username' column.

In [26]:
df=p.DataFrame({'Email':['john@example.com','sarah@company.net','david@school.edu','lisa@blog.org','mike@consulting.co.uk']})

In [27]:
df

                   Email
0       john@example.com
1      sarah@company.net
2       david@school.edu
3          lisa@blog.org
4  mike@consulting.co.uk

In [28]:
def get_username(df):
    df['Username']=df['Email'].apply(lambda x:x.split('@')[0])
    return df

In [29]:
get_username(df)

                   Email Username
0       john@example.com     john
1      sarah@company.net    sarah
2       david@school.edu    david
3          lisa@blog.org     lisa
4  mike@consulting.co.uk     mike

Q8. You have a Pandas DataFrame df with columns 'A', 'B', and 'C'. Write a Python function that selects
all rows where the value in column 'A' is greater than 5 and the value in column 'B' is less than 10. The
function should return a new DataFrame that contains only the selected rows.
For example, if df contains the following values:

A B C

0 3 5 1

1 8 2 7

2 6 9 4

3 2 3 5

4 9 1 2

Your function should select the following rows: A B C

1 8 2 7

4 9 1 2

The function should return a new DataFrame that contains only the selected rows.

In [30]:
df=p.DataFrame({'a':[3,8,6,2,9],'b':[5,2,9,3,1],'c':[1,7,4,5,2]})

In [31]:
df

   a  b  c
0  3  5  1
1  8  2  7
2  6  9  4
3  2  3  5
4  9  1  2

In [32]:
def select(df):
    val=(df['a']>5)&(df['c']<10)
    new_df=df[val]
    return new_df

In [33]:
new=select(df)

new

## Q9. Given a Pandas DataFrame df with a column 'Values', write a Python function to calculate the mean,median, and standard deviation of the values in the 'Values' column.

In [34]:
def calculations(df):
    print('mean : ',df['values'].mean())
    print('median : ',df['values'].median())
    print('Standard daviation : ',df['values'].std())

In [35]:
df=p.DataFrame({'values':[1,2,3,4,5,6,7]})

In [36]:
calculations(df)

mean :  4.0
median :  4.0
Standard daviation :  2.160246899469287

## Q10. Given a Pandas DataFrame df with a column 'Sales' and a column 'Date', write a Python function to create a new column 'MovingAverage' that contains the moving average of the sales for the past 7 days for each row in the DataFrame. The moving average should be calculated using a window of size 7 and should include the current day.

In [37]:
def add_moving_average(df):
    df.set_index('Date', inplace=True)
    df['MovingAverage'] = df['Sales'].rolling(window=7, min_periods=1).mean()
    df.reset_index(inplace=True)

    return df

## Q11. You have a Pandas DataFrame df with a column 'Date'. Write a Python function that creates a new column 'Weekday' in the DataFrame. The 'Weekday' column should contain the weekday name (e.g.Monday, Tuesday) corresponding to each date in the 'Date' column.
For example, if df contains the following values:
Date

0 2023-01-01

1 2023-01-02

2 2023-01-03

3 2023-01-04

4 2023-01-05

Your function should create the following DataFrame:

Date Weekday

0 2023-01-01 Sunday

1 2023-01-02 Monday

2 2023-01-03 Tuesday

3 2023-01-04 Wednesday

4 2023-01-05 Thursday

The function should return the modified DataFrame.

In [46]:
def getdays(df):
    df['Date']=p.to_datetime(df['Date'])
    df['Weekday']=df['Date'].dt.day_name()
    return df

In [47]:
df4=p.DataFrame({'Date':['2023-01-01','2023-01-02','2023-01-03','2023-01-04','2023-01-05']})

In [48]:
getdays(df4)

        Date    Weekday
0 2023-01-01     Sunday
1 2023-01-02     Monday
2 2023-01-03    Tuesday
3 2023-01-04  Wednesday
4 2023-01-05   Thursday

## Q12. Given a Pandas DataFrame df with a column 'Date' that contains timestamps, write a Python function to select all rows where the date is between '2023-01-01' and '2023-01-31'.

In [51]:
def select_date_range(df):
    df['Date'] = p.to_datetime(df['Date'])
    mask = (df['Date'] >= '2023-01-01') & (df['Date'] <= '2023-01-31')
    selected_df = df.loc[mask]
    return selected_df

In [52]:
print(select_date_range(df4))

        Date    Weekday
0 2023-01-01     Sunday
1 2023-01-02     Monday
2 2023-01-03    Tuesday
3 2023-01-04  Wednesday
4 2023-01-05   Thursday

## Q13. To use the basic functions of pandas, what is the first and foremost necessary library that needs to be imported?

## The mostimportant library that we have to import is " pandas"